version: '3.9'
services:
  postgres:
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB= postgresql
      - POSTGRES_USER= SergKry
      - POSTGRES_PASSWORD= Necro12
    volumes:
      - ./data:/var/lib/postgresql/data